version: "3.8"

services:
  postgres:
    container_name: task-check-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: task-check
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
